name: GitHub Pages Deploy

on:
  push:
    branches:
      - "master"


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.17 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Add route for gh pages base path
        run: mkdir ./src/routes/dev-profile && cp ./src/routes/index.tsx ./src/routes/dev-profile

      - name: Build page
        run: npm install && npm run gh-pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist/public